### PR TITLE
Added new columns to timeperiods table

### PR DESCRIPTION
**Pull request by sidhartha-sankar**
op5 specific:
The availability and sla reports do not show any data.
The reason for this is lack of few columns.

### CODE REVIEW

**Comment by sni** [comment]
Interesting, didn't know these fields exist. That opens new possibilities... :-)
Are those fields really dynamic and can change during runtime? If not, please change them to `StaticUpdate`.

**Comment by sidhartha-sankar** [comment]
I think these list types can get modified after inputs from gui for reports.

**Comment by sni** [comment]
No, you cannot. The only thing you can change from an external command is assigning a new timeperiod to hosts/services and contacts. Could you please change them to static then?

**Comment by sidhartha-sankar** [comment]
yah sure. would change them to static.

**Comment by sidhartha-sankar** [comment]
Updated!

**Comment by sni** [comment]
squashed and merged with 104e33aeb

thanks

**Pull request closed without merging**
