### PR TITLE
Add StatsNegate Support

### PR DESCRIPTION
**Pull request by jdumalaonITRS**
This commit adds StateNegate functionality which follows the Negate implementation.
It also fixes an issue where Negate/StatsNegate is not applied on the GroupOperator level which is supported in Livestatus

### CODE REVIEW

**Comment by sni** [comment]
thanks, looks good so far. Could you have a look at the ci tests please?

**Comment by jdumalaonITRS** [comment]
Thanks. Yup I will work on the failing ci tests.

**Comment by sni** [comment]
btw, you can run the citests locally my "make citest" or "make golangci" if you only want to run the golangci checks.

**Comment by jdumalaonITRS** [comment]
Yup just saw it now. I will do so

**Comment by sni** [comment]
should be fine now, but somehow i cannot rebase this PR.

**Comment by jdumalaonITRS** [comment]
thanks. No worries. I rebased the changes

**Review by sni — APPROVED** [review]

**Comment by sni** [comment]
thanks, looks fine.

**Pull request merged**
