### PR TITLE
Update objects.go

### PR DESCRIPTION
**Pull request by sidhartha-sankar**
Naemon specific parameters in the GET comments request.
These requests have host or service specific parameters which are ignored by LMD. 
Hence made it naemon specific.

### CODE REVIEW

**Comment by sni** [comment]
I'd say it would be better to just add references, ex.: `t.AddRefColumn("hosts", "host", "name", "host_name")`, then you would have access to all host and service attributes.

**Comment by sni** [comment]
Also please do those changes to comments and downtimes.

**Comment by sidhartha-sankar** [comment]
Added the references in comments and downtimes. But in case of comments still some parameters like "host_has_been_checked" needs to be added as these are not present in hosts table and livestatus gives valid replies to these parameters.

**Comment by sni** [comment]
I don't know where you have looked, but `has_been_checked` and `state` are present in the hosts and services table. There is no need to duplicate data here.

**Comment by sidhartha-sankar** [comment]
Yes `has_been_checked` and `state` are present. But the request host is making with parameters are `host_has_been_checked` and `host_state`  which are not present.

**Comment by sidhartha-sankar** [comment]
Removed  earlier added addref columns. Those created timeout issues in test.

**Comment by sni** [comment]
with the commit above, all host and service attributes are available from within comments and downtimes.

**Pull request closed without merging**
